// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using 員工資料管理.Models;

#nullable disable

namespace 員工資料管理.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240807061236_test3")]
    partial class test3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("員工資料管理.Models.員工資料模型", b =>
                {
                    b.Property<int>("員工編號")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("員工編號"));

                    b.Property<string>("LDF_操作權限")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LDF_登入密碼")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("住家地址")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("住家電話")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("備註")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("出生日期")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("到職日期")
                        .HasColumnType("datetime2");

                    b.Property<string>("員工姓名")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("啟停狀態0停用1啟用")
                        .HasColumnType("bit");

                    b.Property<string>("字串一")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("字串三")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("字串二")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("學歷")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("小數一")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("小數三")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("小數二")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("建檔人")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("建檔日期")
                        .HasColumnType("datetime2");

                    b.Property<string>("性別")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("擴展欄位")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("檔附件")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("照片")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("聯絡人姓名")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("聯絡人電話")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("職務")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("行動電話")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("身分證號")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("軟體權限群組")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("軟體登入密碼")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("軟體登入帳號")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("軟體登入權限")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("通訊地址")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("通訊電話")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("邏輯一")
                        .HasColumnType("bit");

                    b.Property<bool?>("邏輯三")
                        .HasColumnType("bit");

                    b.Property<bool?>("邏輯二")
                        .HasColumnType("bit");

                    b.Property<string>("部門")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("離職日期")
                        .HasColumnType("datetime2");

                    b.HasKey("員工編號");

                    b.ToTable("員工資料");
                });
#pragma warning restore 612, 618
        }
    }
}
